### ISSUE TITLE
Crash whenever I put anything into the rucksack/storage in camping inventory

### ISSUE THREAD

**Issue by mahilo3550** [Rikmuld/MC-Camping#100]
I can use the rucksack while it's in my hand just fine. If I access it via the tab in the Camping Inventory, the game will immediate crash if I shift-right click something into the inventory, manually click and drag something into the inventory, or click on anything in that inventory. I really like the idea of having extra storage that doesn't need to be in your hotbar to access it, so this pretty much cancels out the reason I downloaded this mod to begin with. :(

PM
Description: Updating screen events

java.lang.AbstractMethodError: com.rikmuld.camping.inventory.SlotTabbedBackpack.onSlotChanged()V
	at com.rikmuld.corerm.inventory.slots.SlotChangingInventory$$anonfun$putStack$1.apply(SlotChangingInventory.scala:17)
	at com.rikmuld.corerm.inventory.slots.SlotChangingInventory$$anonfun$putStack$1.apply(SlotChangingInventory.scala:15)
	at scala.Option.foreach(Option.scala:245)
	at com.rikmuld.corerm.inventory.slots.SlotChangingInventory$class.putStack(SlotChangingInventory.scala:15)
	at com.rikmuld.camping.inventory.SlotTabbedBackpack.func_75215_d(Slots.scala:83)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:281)
	at com.rikmuld.camping.inventory.camping.ContainerCamping.func_184996_a(Camping.scala:76)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:604)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:543)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Rikmuld** [comment]
Strange error, doesn't happen in a development environment. Fixed with https://github.com/Rikmuld/MC-RMCore/commit/5966bc86e72aab6eec1fc1ea2563e3b522397e20. Expect an update later today.
