### ISSUE TITLE
Server Crash on startup - version 2.4.1

### ISSUE THREAD

**Issue by Rutes** [Rikmuld/MC-Camping#117]
Hello again! Looks like with this new version I'm getting a crash on startup of my server. I removed Sponge and several other mods, but still happening.

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 4/24/18 5:59 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from The Camping Mod 2 (camping)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.rikmuld.camping.features.inventory_camping.EventsClient
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:578)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.rikmuld.camping.features.inventory_camping.EventsClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	... 31 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@2fb68ec6 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 37 more
Caused by: java.lang.RuntimeException: Attempted to load class com/rikmuld/camping/features/inventory_camping/EventsClient for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.13.0-38-generic
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 20904550712 bytes (19936 MB) / 21474836480 bytes (20480 MB) up to 21474836480 bytes (20480 MB)
	JVM Flags: 13 total; -Xms20G -Xmx20G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=35 -XX:G1MaxNewSizePercent=70 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AggressiveOpts -XX:+AlwaysPreTouch
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.3.2655 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version         | Source                                        | Signature                                |
	|:----- |:--------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft             | 1.12.2          | minecraft.jar                                 | None                                     |
	| UC    | mcp                   | 9.42            | minecraft.jar                                 | None                                     |
	| UC    | FML                   | 8.0.99.99       | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge                 | 14.23.3.2655    | forge.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | biomesoplenty         | 7.0.1.2381      | BiomesOPlenty-1.12.2-7.0.1.2381-universal.jar | None                                     |
	| UC    | craftstudioapi        | 1.0.0           | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| UC    | animania              | 1.4.7           | animania-1.12.2-1.4.8.jar                     | None                                     |
	| UC    | antiqueatlas          | 4.4.7           | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UC    | examplemod            | 1.0             | antiqueatlas-1.12.2-4.4.7.jar                 | None                                     |
	| UC    | architecturecraft     | @VERSION@       | architecturecraft-1.12-2.68.jar               | None                                     |
	| UC    | bibliocraft           | 2.4.3           | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UC    | cameraobscura         | 0.0.1           | CameraObscura-1.0.3.jar                       | None                                     |
	| UC    | carryon               | 1.8             | CarryOn MC1.12.2 v1.8.jar                     | None                                     |
	| UC    | chameleon             | 1.12-4.1.3      | Chameleon-1.12-4.1.3.jar                      | None                                     |
	| UC    | clayworldgen          | 1.1.0-1.12      | ClayWorldGen-1.1.0-1.12.0.jar                 | None                                     |
	| UC    | cosmeticarmorreworked | 1.12.2-v1       | CosmeticArmorReworked-1.12.2-v1.jar           | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UC    | craftablehorsearmour  | 1.3             | CraftableHorseArmour-1.3.0-1.12.jar           | None                                     |
	| UC    | ptrmodellib           | 1.0.2           | PTRLib-1.0.2.jar                              | None                                     |
	| UC    | props                 | 2.6.0           | Decocraft-2.6.0_1.12.2.jar                    | None                                     |
	| UC    | doggytalents          | 1.14.2.314      | DoggyTalents-1.12-1.14.2.314-universal.jar    | None                                     |
	| UC    | dynamictrees          | 1.12.2-0.7.6    | DynamicTrees-1.12.2-0.7.6.jar                 | None                                     |
	| UC    | dynamictreesbop       | 1.0.0           | dynamictreesbop-1.0.0.jar                     | None                                     |
	| UC    | fairylights           | 2.1.2           | fairylights-2.1.2-1.12.x.jar                  | None                                     |
	| UC    | familiarfauna         | 1.0.7           | FamiliarFauna-1.12.2-1.0.7.jar                | None                                     |
	| UC    | fastleafdecay         | v14             | FastLeafDecay-v14.jar                         | None                                     |
	| UC    | fenceoverhaul         | 1.3.4           | FenceOverhaul-1.3.4.jar                       | None                                     |
	| UC    | guideapi              | 1.12-2.1.5-60   | Guide-API-1.12-2.1.5-60.jar                   | None                                     |
	| UC    | horsepower            | 2.6.1           | HorsePower-1.12.2-2.6.1.62.jar                | cd7e958342770a8b17c919055da42c24dfefd879 |
	| UC    | jaff                  | 1.7_for_1.12    | JustAFewFish-1.7_for_1.12.jar                 | None                                     |
	| UC    | kleeslabs             | 5.4.9           | KleeSlabs_1.12.2-5.4.9.jar                    | None                                     |
	| UC    | lessforgivingvoid     | 1.0.1           | LessForgivingVoid-1.0.1.jar                   | None                                     |
	| UC    | maille                | 2.0             | Maille1.12.2-2.0.jar                          | None                                     |
	| UC    | mantle                | 1.12-1.3.2.24   | Mantle-1.12-1.3.2.24.jar                      | None                                     |
	| UC    | morpheus              | 1.12-3.3.2      | Morpheus-1.12-3.3.2.jar                       | None                                     |
	| UC    | openglider            | @VERSION@       | OpenGlider-1.12.1-1.1.0.jar                   | None                                     |
	| UC    | petbat                | 1.4.8           | PetBat-1.12.2.jar                             | None                                     |
	| UC    | corerm                | 1.3.1           | RikMuldsCore_1.3.1.jar                        | None                                     |
	| UC    | rustic                | 1.0.3           | rustic-1.0.3.jar                              | None                                     |
	| UC    | sophisticatedwolves   | 3.13.2          | SophisticatedWolves-1.12.2-3.13.2.jar         | None                                     |
	| UC    | storagedrawers        | 1.12-5.3.5      | StorageDrawers-1.12.2-5.3.6.jar               | None                                     |
	| UC    | tconstruct            | 1.12.2-2.9.1.65 | TConstruct-1.12.2-2.9.1.65.jar                | None                                     |
	| UC    | tfa                   | 1.1.2           | TFA 1.3.jar                                   | None                                     |
	| UE    | camping               | 2.4.1           | TheCampingMod_2.4.1.jar                       | None                                     |
	| UC    | tombstone             | 2.9.0           | tombstone-2.9.0-1.12.jar                      | None                                     |
	| UC    | totemic               | 1.12.2-0.10.3   | Totemic-1.12.2-0.10.3.jar                     | 21d11d7bf4d97b465382a1f95428029aac6daaea |

	Loaded coremods (and transformers): 
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Rikmuld** [comment]
Sorry about that, in my hurry I forgot to check whether or not the server side worked properly. I'll update in a bit.
