### ISSUE TITLE
Minecraft Keeps crashing because of this mod 

### ISSUE THREAD

**Issue by 2cute2kill** [Rikmuld/MC-Camping#86]
heres the crash report. i looked it up on minecraft forum and they said that it was your mod and to send you this crash report

---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (Better-Foliage-Mod-1.8.9.jar)
  CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  MovingWorldCoreMod (movingworld-MC1.8.9-V1.9-full.jar)
  SeasonsPreLoader (SeasonsAPI-1.0.3b.jar)
  ThaumcraftLoader (Thaumcraft-1.8.9-5.1.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 10/7/16 9:08 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Random.java:388)
    at com.rikmuld.camping.world.WorldGenerator.generateSurface(WorldGenerator.scala:40)
    at com.rikmuld.camping.world.WorldGenerator.generate(WorldGenerator.scala:23)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1068)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at net.minecraft.world.SpawnerAnimals.func_180267_a(SpawnerAnimals.java:189)
    at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:122)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:199)
    at WorldServerOF.func_72835_b(WorldServerOF.java:37)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:251)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.Random.nextInt(Random.java:388)
    at com.rikmuld.camping.world.WorldGenerator.generateSurface(WorldGenerator.scala:40)
    at com.rikmuld.camping.world.WorldGenerator.generate(WorldGenerator.scala:23)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:262)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1068)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12)
    at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344)
    at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:109)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:84)
    at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:181)
    at net.minecraft.world.World.func_72964_e(World.java:287)
    at net.minecraft.world.World.func_175726_f(World.java:282)
    at net.minecraft.world.World.func_180495_p(World.java:822)
    at net.minecraft.world.SpawnerAnimals.func_180267_a(SpawnerAnimals.java:189)
    at net.minecraft.world.SpawnerAnimals.func_77192_a(SpawnerAnimals.java:122)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:199)
    at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
    Level name: Historia
    All players: 1 total; [EntityPlayerMP['x2cute2killx'/268, l='Historia', x=93.30, y=67.00, z=764.39]]
    Chunk stats: ServerChunkCache: 504 Drop: 29
    Level seed: 1177476785
    Level generator: ID 04 - customized, ver 0. Features enabled: true
    Level generator options: {"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":80.0,"mainNoiseScaleY":160.0,"mainNoiseScaleZ":80.0,"baseSize":8.5,"stretchY":12.0,"biomeDepthWeight":1.0,"biomeDepthOffset":0.0,"biomeScaleWeight":1.0,"biomeScaleOffset":0.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":100,"useStrongholds":true,"useVillages":true,"useMineShafts":true,"useTemples":true,"useMonuments":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":4,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":5,"riverSize":5,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":80,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":80,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":80,"coalSize":27,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":128,"ironSize":21,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":64,"goldSize":15,"goldCount":5,"goldMinHeight":0,"goldMaxHeight":32,"redstoneSize":16,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":16,"diamondSize":15,"diamondCount":6,"diamondMinHeight":0,"diamondMaxHeight":16,"lapisSize":16,"lapisCount":5,"lapisCenterHeight":16,"lapisSpread":16}
    Level spawn location: 116.00,64.00,256.00 - World: (116,64,256), Chunk: (at 4,4,0 in 7,16; contains blocks 112,0,256 to 127,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 1216590 game time, 8546 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 114089 (now: false), thunder time: 69842 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:690)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:251)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 8.1 (amd64) version 6.3
    CPU: 4x AMD A6-5200 APU with Radeon(TM) HD Graphics
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 191406032 bytes (182 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
    FML: MCP 9.19 Powered by Forge 11.15.1.1902 Optifine OptiFine_1.8.9_HD_U_H6 25 mods loaded, 24 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar)
    UCHIJAAAA   darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE](minecraft.jar)
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.8.9-11.15.1.1902-1.8.9.jar)
    UCHIJAAAA   Forge{11.15.1.1902} [Minecraft Forge](forge-1.8.9-11.15.1.1902-1.8.9.jar)
    UCHIJAAAA   MovingWorld{MC1.8.9-V1.9} [Moving World](movingworld-MC1.8.9-V1.9-full.jar)
    UCHIJAAAA   ArchimedesShipsPlus{MC1.8.9-V1.9} [Archimedes' Ships Plus](archimedesshipsplus-MC1.8.9-V1.9-full.jar)
    UCHIJAAAA   backpack{3.0.1} [Backpack](backpack-3.0.1-1.8.9.jar)
    UCHIJAAAA   BetterFoliage{2.0.12} [Better Foliage](Better-Foliage-Mod-1.8.9.jar)
    UCHIJAAAA   BiblioCraft{2.0.1} [BiblioCraft](BiblioCraft[v2.0.1][MC1.8.9].jar)
    UCHIJAAAA   cfm{4.0.1} [MrCrayfish's Furniture Mod](cfm-4.0.1-mc1.8.9.jar)
    UCHIJAAAA   doggytalents{v1.10.0a} [Doggy Talents](DoggyTalents-1.8.9-v1.10.0a-universal.jar)
    UCHIJAAAA   excore{1.5.3} [EXCore](Excore-1.5.3-1.8.9.jar)
    UCHIJAAAA   JEI{2.28.18.186} [Just Enough Items](jei_1.8.9-2.28.18.186.jar)
    UCHIJAAAA   Baubles{1.1.3.0} [Baubles](Baubles-1.8.9-1.1.3.0.jar)
    UCHIJAAAA   FEI{1.0.10} [Forever Enough Items](ForeverEnoughItems-1.0.10-1.8.9.jar)
    UCHIJAAAA   mantle{1.8.9-0.9.2.jenkins102} [Mantle](Mantle-1.8.9-0.9.2.jar)
    UCHIJAAAA   minecolonies{1.8.9-0.4.737} [MineColonies](MineColonies-Mod-1.8.9.jar)
    UCHIJAAAA   MoCreatures{8.2.1} [DrZhark's Mo'Creatures Mod](Mo'Creatures Mod-8.2.1.jar)
    UCHIJAAAA   reforged{0.6.1} [Reforged](reforged-0.6.1-alpha-1.8.9.jar)
    UCHIJAAAA   corerm{1.2e-1.8.9} [RikMuld's Core](RikMuldsCore_1.2e-1.8.9.jar)
    UCHIJAAAA   seasonsapi{1.0.3b} [Seasons API](SeasonsAPI-1.0.3b.jar)
    UCHIJAAAA   tconstruct{1.8.9-2.2.1.jenkins1005} [Tinkers' Construct](TConstruct-1.8.9-2.2.1.jar)
    UCHIJAAAA   Thaumcraft{5.1.0} [Thaumcraft](Thaumcraft-1.8.9-5.1.0.jar)
    UCHIJAAAA   camping{2.3d-1.8.9} [The Camping Mod 2](TheCampingMod_2.3d-1.8.9.jar)
    UD  seasonsAPIPreloader{Seasons API Preloader} [Seasons API Preloader](minecraft.jar)
    Loaded coremods (and transformers):
BetterFoliageLoader (Better-Foliage-Mod-1.8.9.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
CCLCorePlugin (CodeChickenLib-1.8-1.1.2.133-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
MovingWorldCoreMod (movingworld-MC1.8.9-V1.9-full.jar)

SeasonsPreLoader (SeasonsAPI-1.0.3b.jar)
  mod.mindcraft.seasons.asm.Transformer
ThaumcraftLoader (Thaumcraft-1.8.9-5.1.0.jar)

```
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
Pulsar/tconstruct loaded Pulses:
    - TinkerCommons (Enabled/Forced)
    - TinkerWorld (Enabled/Not Forced)
    - TinkerTools (Enabled/Not Forced)
    - TinkerSmeltery (Enabled/Not Forced)
    - TinkerGadgets (Enabled/Not Forced)
    - TinkerOredict (Enabled/Forced)
    - TinkerIntegration (Enabled/Forced)
    - TinkerFluids (Enabled/Forced)
    - TinkerMaterials (Enabled/Forced)

Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['x2cute2killx'/268, l='Historia', x=93.30, y=67.00, z=764.39]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
OptiFine Version: OptiFine_1.8.9_HD_U_H6
Render Distance Chunks: 4
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.2.12422 Compatibility Profile Context 13.152.0.0
OpenGlRenderer: AMD Radeon HD 8400
OpenGlVendor: ATI Technologies Inc.
CpuCount: 4
```

**Comment by llamositopia** [comment]
Could you post the config file you have for this mod?

**Comment by Rikmuld** [comment]
Indeed happend because some config option was put to a negative number, added a safety check now so this won't happen again.
